# Generated by Django 2.2 on 2022-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=20)),
                ('squad_start', models.DateTimeField()),
                ('squad_last', models.DateTimeField()),
                ('reputation', models.IntegerField()),
                ('prospect', models.IntegerField()),
                ('church', models.IntegerField()),
            ],
        ),
    ]
