# Generated by Django 2.2 on 2022-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='squad_desc',
            field=models.CharField(default='Noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='squad',
            name='church',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='prospect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_last',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_name',
            field=models.CharField(default='Noname', max_length=40),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
