# Generated by Django 2.2 on 2022-06-11 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220611_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='squad_last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 21, 42, 10, 509080)),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 21, 42, 10, 509047)),
        ),
    ]
