# Generated by Django 2.2 on 2022-06-12 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220611_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliableQuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.IntegerField()),
                ('expansion', models.IntegerField()),
                ('mission', models.CharField(blank=True, default=None, max_length=10)),
                ('finished', models.BooleanField()),
                ('blocked', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 15, 47, 54, 910166)),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 15, 47, 54, 910134)),
        ),
    ]
